### ISSUE TITLE
Button design

### ISSUE THREAD

**Issue by theotherstevenc** [email-markup-consortium/email-reader-view#17]
Make them prettier while remaining accessible

**Comment by M-J-Robbins** [comment]
Quick idea 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/7871206/232240570-b5da8c8c-bb96-46ca-8d09-fb41a7937818.png">

```css
button.button{
  width:15em;
  border-radius:.4em;
  display:block;
  margin:.5em auto;
  background-image:linear-gradient(hsl(185, 77%, 27%) 20%, hsl(185, 77%, 22%));
  border:.1em solid hsl(185, 77%, 20%);
  text-shadow: -1px -1px hsl(185, 77%, 20%), 1px 1px hsl(185, 77%, 27%);
  color:#fff;
}
button.button:hover,
button.button:focus{
  background-image:linear-gradient(hsl(185, 77%, 22%), hsl(185, 77%, 27%) 80%);
  text-shadow: 1px 1px hsl(185, 77%, 20%), -1px -1px hsl(185, 77%, 27%);
}
```

<img width="299" alt="image" src="https://user-images.githubusercontent.com/7871206/232241179-bfaa8a9b-f77a-4088-a1eb-aa6a0187e606.png">

```css
button.button.off{
  background-image:linear-gradient(hsl(185, 17%, 27%) 20%, hsl(185, 17%, 22%));
  border:.1em solid hsl(185, 17%, 20%);
}
button.button:hover,
button.button:focus{
  background-image:linear-gradient(hsl(185, 17%, 22%), hsl(185, 17%, 27%) 80%);
}
```
